#!/bin/bash

PWD="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLASSDIR="$(echo $PWD | cut -d '/' -f 1-5)"
CLASS="$(basename $CLASSDIR)"
ASG="$(basename $PWD)"
ASGBIN="$CLASSDIR/bin/$ASG"
ASGDIR="$CLASSDIR/$ASG"
SEPARATE="=================================================="

forall() {
  cd $ASGDIR
  for STUDENT in $(ls -d */); do
    STUDENT=$(basename $STUDENT /)
    STUDENTDIR=$ASGDIR/$STUDENT
    cd $STUDENTDIR
    #echo -ne "$STUDENT     \t"
    pwd
	$@
  done
}

if [[ $@ ]]; then
  forall $@
else
  echo "forall: run forall directories in $ASGDIR"
  echo "Enter a command, or nothing to exit."
  echo -n "$ "
  read INPUT
  if [[ $INPUT ]]; then
	  forall $INPUT
  fi
fi
