#!/bin/bash

CLASS=$(pwd | cut -d '/' -f 1-5)
ASG=$(basename $(pwd))
ASGBIN="$CLASS/bin/$ASG"
ASGDIR="$CLASS/$ASG"
SEPARATE="=================================================="

forall() {
  cd $ASGDIR
  for STUDENTDIR in $(ls -d */); do
    STUDENT=$(basename $STUDENTDIR /)
    STUDENTDIR=$ASGDIR/$STUDENT
    cd $STUDENTDIR
    echo -ne "$STUDENT     \t"
    $@
  done
}

if [[ $@ ]]; then
  forall $@
else
  echo "USAGE: forall COMMAND"
  echo "Runs COMMAND forall students in $CLASS/$ASG"
fi
